/*
 * FrameView.java
 *
 * Created on 21. maaliskuuta 2008, 11:56
 */

package fi.kaimio.moviescan.ui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.RenderedImage;
import javax.media.jai.operator.ScaleDescriptor;

/**
 Simple viewer component for movie frames.
 
 @author  harri
 */
public class FrameView extends javax.swing.JPanel {
    
    /** Creates new form FrameView */
    public FrameView() {
        initComponents();
    }
 
    /**
     The image to show
     */
    RenderedImage img;
    
    /**
     Cached copy scaled to the screen resolution.
     */
    RenderedImage scaledImage = null;
    
    /**
     Set the image displayed in this window
     @param img The image to display
     */
    public void setImage( RenderedImage img ) {
        this.img = img;
        scaledImage = null;
        repaint();
    }
    
    /**
     Get the currently displayed image.
     @return
     */
    public RenderedImage getImage() {
        return img;
    }
    
    
    @Override
    public void paint( Graphics g ) {
        super.paint(g);
        if ( img == null ) {
            return;
        }
        if ( scaledImage == null ) {
            float scaleH = (float)getWidth()/(float)img.getWidth();
            float scaleV = (float)getHeight()/(float)img.getHeight();
            float scale = Math.min( scaleV, scaleH );
            scaledImage = ScaleDescriptor.create(img, scale, scale, 0.0f, 0.0f, null, null);
        }
        ((Graphics2D)g).drawRenderedImage(scaledImage, AffineTransform.getScaleInstance(1.0, 1.0));
    }
    
    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
