/*
 * MainWindow.java
 *
 * Created on 21. maaliskuuta 2008, 11:11
 */

package fi.kaimio.moviescan.ui;

import fi.kaimio.moviescan.FrameDescriptor;
import fi.kaimio.moviescan.FrameIterator;
import fi.kaimio.moviescan.Project;
import java.awt.image.RenderedImage;
import java.io.File;
import javax.swing.JOptionPane;

/**
 
 @author  harri
 */
public class MainWindow extends javax.swing.JFrame {
    
    Project prj;
    
    FrameIterator projectIter;
    
    ScanStripView stripViewer;
    
    RenderedImage currentImage = null;
    
    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        stripViewer = (ScanStripView) stripView;
        prj = Project.getProject( new File( "/home/harri/s8/tuhkimo" ) );
        projectIter = (FrameIterator) prj.iterator();
    }
    
    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        frameViewModeGroup = new javax.swing.ButtonGroup();
        framePane = new FrameView();
        stripView = new ScanStripView();
        jPanel1 = new javax.swing.JPanel();
        blackSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        whiteSlider = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        frameNumField = new javax.swing.JTextField();
        goToFrameBtn = new javax.swing.JButton();
        nextFrameBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jToolBar2 = new javax.swing.JToolBar();
        perfViewModeBtn = new javax.swing.JToggleButton();
        frameViewModeBtn = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        framePane.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout framePaneLayout = new javax.swing.GroupLayout(framePane);
        framePane.setLayout(framePaneLayout);
        framePaneLayout.setHorizontalGroup(
            framePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );
        framePaneLayout.setVerticalGroup(
            framePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout stripViewLayout = new javax.swing.GroupLayout(stripView);
        stripView.setLayout(stripViewLayout);
        stripViewLayout.setHorizontalGroup(
            stripViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );
        stripViewLayout.setVerticalGroup(
            stripViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));

        blackSlider.setMaximum(1000);
        blackSlider.setValue(0);
        blackSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blackSliderStateChanged(evt);
            }
        });

        jLabel4.setText("White");

        whiteSlider.setMaximum(65535);
        whiteSlider.setValue(65535);
        whiteSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                whiteSliderStateChanged(evt);
            }
        });

        jLabel5.setText("Black");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(whiteSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(blackSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(whiteSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blackSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setText("Frame");

        goToFrameBtn.setText("Go");
        goToFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToFrameBtnActionPerformed(evt);
            }
        });

        nextFrameBtn.setText("Next");
        nextFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextFrameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goToFrameBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextFrameBtn)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(frameNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(goToFrameBtn)
                .addComponent(nextFrameBtn))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        frameViewModeGroup.add(perfViewModeBtn);
        perfViewModeBtn.setText("Perforation");
        perfViewModeBtn.setFocusable(false);
        perfViewModeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        perfViewModeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        perfViewModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfViewModeBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(perfViewModeBtn);

        frameViewModeGroup.add(frameViewModeBtn);
        frameViewModeBtn.setSelected(true);
        frameViewModeBtn.setText("Frame");
        frameViewModeBtn.setFocusable(false);
        frameViewModeBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        frameViewModeBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        frameViewModeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frameViewModeBtnActionPerformed(evt);
            }
        });
        jToolBar2.add(frameViewModeBtn);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stripView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(framePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stripView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(framePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextFrameBtnActionPerformed
        if ( projectIter.hasNext() ) {
            FrameDescriptor d = projectIter.next();
            currentImage = d.getFrame();
            frameNumField.setText( Integer.toString( projectIter.getCurrentFrameNum() ));
            ((FrameView)framePane).setFrame( d );
            stripViewer.setStrip( d.getStrip() );
            stripViewer.setSelectedFrame( d.getStripFrameNum() );
        }
}//GEN-LAST:event_nextFrameBtnActionPerformed

    private void goToFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToFrameBtnActionPerformed
        try {
            int frame = Integer.parseInt( frameNumField.getText() );
            projectIter.setNextFrameNum( frame );
            nextFrameBtnActionPerformed( evt );
        } catch ( NumberFormatException e ) {
            JOptionPane.showMessageDialog( this,
                    "Frame number must be number", "Incorrect frame number",
                    JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_goToFrameBtnActionPerformed

    private void whiteSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_whiteSliderStateChanged
        int val = whiteSlider.getValue();
        ((FrameView) framePane).setWhite( val );
    }//GEN-LAST:event_whiteSliderStateChanged

    private void blackSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blackSliderStateChanged
        int val = blackSlider.getValue();
        ((FrameView) framePane).setBlack( val );
}//GEN-LAST:event_blackSliderStateChanged

    private void frameViewModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frameViewModeBtnActionPerformed
        ((FrameView) framePane).setMode( FrameViewMode.DRAW_FRAME );
    }//GEN-LAST:event_frameViewModeBtnActionPerformed

    private void perfViewModeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfViewModeBtnActionPerformed
        ((FrameView) framePane).setMode( FrameViewMode.DRAW_PERFORATION );
    }//GEN-LAST:event_perfViewModeBtnActionPerformed
    
    /**
     @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider blackSlider;
    private javax.swing.JTextField frameNumField;
    private javax.swing.JPanel framePane;
    private javax.swing.JToggleButton frameViewModeBtn;
    private javax.swing.ButtonGroup frameViewModeGroup;
    private javax.swing.JButton goToFrameBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton nextFrameBtn;
    private javax.swing.JToggleButton perfViewModeBtn;
    private javax.swing.JPanel stripView;
    private javax.swing.JSlider whiteSlider;
    // End of variables declaration//GEN-END:variables
    
}
