/*
 * SaveFramesDlg.java
 *
 * Created on 28. maaliskuuta 2008, 21:28
 */

package org.freecine.swingui;

import org.freecine.filmscan.Project;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ApplicationContext;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.Task;
import org.jdesktop.application.TaskEvent;
import org.jdesktop.application.TaskListener;

/**
 Dialog for setting up saving of the frames
 @author  harri
 */
public class SaveFramesDlg extends javax.swing.JDialog {
    private Project project;
    
    /** Creates new form SaveFramesDlg */
    public SaveFramesDlg(java.awt.Frame parent, Project prj, boolean modal) {
        super(parent, modal);
        this.project = prj;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dirNameField = new javax.swing.JTextField();
        widthField = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        heightField = new javax.swing.JFormattedTextField();
        progressBar = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        selectDirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.freecine.swingui.Moviescan.class).getContext().getResourceMap(SaveFramesDlg.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        dirNameField.setText(resourceMap.getString("dirNameField.text")); // NOI18N
        dirNameField.setName("dirNameField"); // NOI18N

        widthField.setText(resourceMap.getString("widthField.text")); // NOI18N
        widthField.setName("widthField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        heightField.setText(resourceMap.getString("heightField.text")); // NOI18N
        heightField.setName("heightField"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.freecine.swingui.Moviescan.class).getContext().getActionMap(SaveFramesDlg.class, this);
        jButton1.setAction(actionMap.get("closeDlg")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton2.setAction(actionMap.get("saveFrames")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        messageLabel.setFont(resourceMap.getFont("messageLabel.font")); // NOI18N
        messageLabel.setText(resourceMap.getString("messageLabel.text")); // NOI18N
        messageLabel.setName("messageLabel"); // NOI18N

        selectDirBtn.setAction(actionMap.get("selectDir")); // NOI18N
        selectDirBtn.setName("selectDirBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dirNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectDirBtn))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dirNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectDirBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeDlg();
    }//GEN-LAST:event_formWindowClosing
    
    /**
     Last task for saving frames
     */
    SaveFramesTask task = null;
    
    /**
     Close the dialog, killing any ongoing background tasks
     */
    @Action
    public void closeDlg() {
        if  ( task != null && !task.isDone() ) {
                task.addTaskListener( new TaskListener.Adapter<Object, Void>() {

                    @Override
                    public void finished( TaskEvent<Void> arg0 ) {
                        setVisible( false );
                    }
                });
                task.cancel( false );                
                   
        } else {
            setVisible( false );
        }
    }

    /**
     Create a background task to save the iamges
     @return A {@link SaveFramesTask} for saving the images
     */
    @Action ( block = Task.BlockingScope.ACTION )
    public Task saveFrames() {
        ApplicationContext ctxt = Application.getInstance().getContext();
        ResourceMap resource = ctxt.getResourceMap( this.getClass() );
        
        File dir = new File( dirNameField.getText() );
        if ( !dir.exists() ) {
            if ( !dir.mkdirs() ) {
                JOptionPane.showMessageDialog( this,
                        resource.getString( "cannotCreateDir.msg", dir.getAbsolutePath() ),
                        resource.getString("cannotCreateDir.title" ), 
                        JOptionPane.ERROR_MESSAGE );
                return null;
            }
        }
        if ( !dir.isDirectory() ) {
            JOptionPane.showMessageDialog( this,
                    resource.getString( "notDir.msg", dir.getAbsolutePath() ),
                    resource.getString( "notDir.title" ),
                    JOptionPane.ERROR_MESSAGE );
            return null;

        }
        
        task = new SaveFramesTask( org.jdesktop.application.Application.getInstance( org.freecine.swingui.Moviescan.class ), project, dir );
        task.addPropertyChangeListener( new PropertyChangeListener() {

            public void propertyChange( PropertyChangeEvent evt ) {
                if ( evt.getPropertyName().equals( "progress" ) ) {
                    progressBar.setValue( ((Number)evt.getNewValue()).intValue() );
                } else if ( evt.getPropertyName().equals( "message" ) ) {
                    messageLabel.setText( task.getMessage() );
                }
            }
        } );
        return task;
    }
    
    /**
     Let the user select a directory for the saved frames using a JFileChooser
     */
    @Action
    public void selectDir() {
        JFileChooser chooser = new JFileChooser();
        ApplicationContext ctxt = Application.getInstance().getContext();
        ResourceMap resource = ctxt.getResourceMap( this.getClass() );
        chooser.setDialogTitle( resource.getString("selectDirDlg.title" ) );
        chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
        if ( chooser.showDialog( this, resource.getString("selectDirDlg.okBtn.text" ) ) == JFileChooser.APPROVE_OPTION ) {
            File dir = chooser.getSelectedFile();
            dirNameField.setText( dir.getPath() );
        }
                    
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dirNameField;
    private javax.swing.JFormattedTextField heightField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton selectDirBtn;
    private javax.swing.JFormattedTextField widthField;
    // End of variables declaration//GEN-END:variables
    
}
